### ISSUE TITLE
Would you mind adding a license?

### ISSUE THREAD

**Issue by stefanhaustein** [chmp/ktwasm#1]
Ideally Apache O:)

**Comment by chmp** [comment]
Sure, can do. I have to study up on the differences between licesens, though. My first instinct would be to choose MIT. Mostly out of habit.

Out of interest, do you have any use case in mind?

**Comment by stefanhaustein** [comment]
MIT SGTM. I am trying to build a reasonable environment for coding on an Android phone: https://github.com/stefanhaustein/tantilla

Currently, it uses an interpreter walking the syntax tree. I'd like to replace this with WASM generation (in the long run -- currently the main focus is a MVP). A Kotlin WASM interpreter seems to be quite useful for this purpose, at least for the transition phase from interpretation to WASM. For instance, I could start with math expressions. 

Open questions: Is there a way to call back to kotlin/Java from the interpreter? Is there a way to pass object references through this path? To my knowledge, WASM doesn't support the latter, but it's something that probably would help the transition significantly.

**Comment by chmp** [comment]
>  A Kotlin WASM interpreter seems to be quite useful for this purpose, at least for the transition phase from interpretation to WASM

TBH. This interpreter is also only a stepping stone for me. As soon as there is an easy to use JIT runtime for WASM on Android, I'll switch. My hope is still that something like [wasmer](https://github.com/wasmerio/wasmer/) will soon support arm targets.

> Open questions: Is there a way to call back to kotlin/Java from the interpreter? 

Short answer: yes. You can import functions from the runtime into WASM. However, at the moment wasm only supports primitive data types (i32, i64, f32, f64). To get around this limitation, you can use pre-allocated memory regions to communicate. In essence, the approach is to serialize all objects sent to WASM into JSON and deserialize all objects retrieved from WASM from JSON. For me it was a bit confusing at first, but re-implementing the wasm-bindgen interface helped me a lot.

For my use case, I compile rust to wasm with [wasm-bindgen](https://github.com/rustwasm/wasm-pack) and re-implement the generated javascript wrapper. You can see an example of that in [my performance tests](https://github.com/chmp/ktwasm/blob/master/src/main/kotlin/de/cprohm/ktwasm/bin/PerformanceTest.kt). 

> MIT SGTM 

I will add a permissive license soonish. As soon as I find some time coding again.

**Comment by chmp** [comment]
I put it the package under MIT license.
